### ISSUE TITLE
Account nonce value is not preserved when using exported genesis.json

### ISSUE THREAD

**Issue by taeguk** [berachain/polaris#1062]
I and our team are building an EVM-compatible chain using Cosmos SDK and Polaris.
We are trying to export genesis.json and run the chain using the exported genesis file.

It seems that the EVM account nonce value is always 0 when running the chain using exported genesis.json.
The behavior that I expect is the nonce value is preserved. But the actual behavior isn't.
Do you have any idea about it?

**Comment by itsdevbear** [comment]
@taeguk did you guys address this? Can you upstream?
