### ISSUE TITLE
secp256k1: unsupported signing algo

### ISSUE THREAD

**Issue by Tore19** [berachain/polaris#1322]
branch: main
commit: b12b9a5f802f221dfedaaaf86e80a92065187d3f

polard keys add test-account-1
Usage:
  simd keys add <name> [flags]

Flags:
      --account uint32           Account number for HD derivation (less than equal 2147483647)
      --coin-type uint32         coin type number for HD derivation (default 60)
      --dry-run                  Perform action, but don't add key to local keystore
      --hd-path string           Manual HD Path derivation (overrides BIP44 config)
  -h, --help                     help for add
      --index uint32             Address index number for HD derivation (less than equal 2147483647)
  -i, --interactive              Interactively prompt user for BIP39 passphrase and mnemonic
      --key-type string          Key signing algorithm to generate keys for (default "secp256k1")
      --ledger                   Store a local reference to a private key on a Ledger device
      --multisig strings         List of key names stored in keyring to construct a public legacy multisig key
      --multisig-threshold int   K out of N required signatures. For use in conjunction with --multisig (default 1)
      --no-backup                Don't print out seed phrase (if others are watching the terminal)
      --nosort                   Keys passed to --multisig are taken in the order they're supplied
      --pubkey string            Parse a public key in JSON format and saves key info to <name> file.
      --recover                  Provide seed phrase to recover existing key instead of creating

Global Flags:
      --home string              directory for config and data (default "/home/stafi/.polard")
      --keyring-backend string   Select keyring's backend (os|file|kwallet|pass|test|memory) (default "os")
      --keyring-dir string       The client Keyring directory; if omitted, the default 'home' directory will be used
      --log_format string        The logging format (json|plain) (default "plain")
      --log_level string         The logging level (trace|debug|info|warn|error|fatal|panic|disabled or '*:<level>,<key>:<level>') (default "info")
      --output string            Output format (text|json) (default "text")
      --trace                    print out full stack trace on errors

8:18AM ERR failure when running app err="secp256k1: unsupported signing algo"

**Comment by corduroybera** [comment]
Please ensure you're running the latest build of polard with the `eth_secp256k1` algo signing option.

Try running these commands:

Make sure you have the latest version of foundry:
```
foundryup
```

Rebuild polard:
```
make build
```

Run the new polard binary:
```
./build/bin/polard keys add test-account-1 --algo eth_secp256k1
```

**Comment by Tore19** [comment]
> Please ensure you're running the latest build of polard with the `eth_secp256k1` algo signing option.
> 
> Try running these commands:
> 
> Make sure you have the latest version of foundry:
> 
> ```
> foundryup
> ```
> 
> Rebuild polard:
> 
> ```
> make build
> ```
> 
> Run the new polard binary:
> 
> ```
> ./build/bin/polard keys add test-account-1 --algo eth_secp256k1
> ```

Hi, it works with `--algo eth_secp256k1`, running the latest build of polard.(Commit: e922486c2428c6e87efe309b9e2dc2b13d1efb28)

```
./build/bin/polard keys add test-account-1 --algo eth_secp256k1
Enter keyring passphrase (attempt 1/3):
Re-enter keyring passphrase:

- address: cosmos18ff49xudcv7l7natejdrnd43nswpfq4xe7eyzz
  name: test-account-1
  pubkey: '{"@type":"/polaris.crypto.ethsecp256k1.v1.PubKey","key":"A+9gktnfGqhckPuVniX9Mumy4UF8fxUoXKKOaL4hqqGj"}'
  type: local

```

But the address prefix is `cosmos`, I think it should be `polaris`, right? Need to add a flag to the cli command?

**Comment by Tore19** [comment]
It uses default cosmos prefix. Requires a code change to set the native address prefix for the chain.
