### ISSUE TITLE
feat(sdk): Committer

### ISSUE THREAD

**Issue by itsdevbear** [berachain/polaris#230]
https://github.com/cosmos/cosmos-sdk/pull/14860

We should get this upstreamed so that we can write the indexed block to the indexer during commit, to ensure that the block will be 100% included in the chain.

**Comment by itsdevbear** [comment]
Not required tbh.

**Comment by calbera** [comment]
Use state streamer? as suggested [here](https://github.com/cosmos/cosmos-sdk/pull/14860#issuecomment-1446451166)

**Comment by calbera** [comment]
If https://github.com/cosmos/cosmos-sdk/pull/14860 is upstreamed, we can move the "finalize block" logic that we currently have in `Prepare` for the next block, to the `Committer`
