### ISSUE TITLE
feat: Pre / Post EVM Hooks

### ISSUE THREAD

**Issue by itsdevbear** [berachain/polaris#483]
@smsunarto volunteered 2 to do so thanks bbg luv u lots. 

Idk what plug-in this shud go into. 

Maybe we make it so u can supply ur own custom ApplyMessage and we make an ExecutionPlugin? But it's very very optional and the default is just standard geth? 

![image](https://user-images.githubusercontent.com/93690142/226121811-9dbe0e3e-9ce2-4bd3-b8d3-9071119a168c.jpeg)

**Comment by itsdevbear** [comment]
@smsunarto u still hitting this?

**Comment by smsunarto** [comment]
will get to this soon ™️

**Comment by itsdevbear** [comment]
😎

**Comment by ameya-deshmukh** [comment]
@smsunarto boss you wanna hand it over to me if you don't got time?

**Comment by smsunarto** [comment]
all yours chief

**Comment by itsdevbear** [comment]
iceboxing this for the time being
