### ISSUE TITLE
feat(cosmos): EIP 1559 / Dynamic Gas

### ISSUE THREAD

**Issue by itsdevbear** [berachain/polaris#484]
This technically should be chain wide. And isn't EVM specific. 

@tac0turtle are we still potentially open to implementing at the SDK level?

**Comment by tac0turtle** [comment]
yes, was talking to dev about this, there is a variation we will look to adopt in the sdk but will enable more chains to build this as well. would love to see where this goes

**Comment by itsdevbear** [comment]
Definitely, I know @MaghnusM mentioned they are doing some stuff as well.

For now we are thinking maybe just do this: https://github.com/berachain/polaris/pull/521

It's a simple change to at least enable eip1559 in the EVM for Polaris, but it won't be enabled broadly in the SDK. If we merge this change, in the future we can add a flag and then use the Cosmos-SDK version on Berachain, in lieu of the built in Polaris version.
