### ISSUE TITLE
imp(testing): improve ginkgo testing structure 

### ISSUE THREAD

**Issue by transmissions12** [berachain/polaris#506]
we have some repetition in terms of chain set up and stuff  and we are doing it before every test.

https://github.com/berachain/polaris/blob/b6bf381996c62abd4ff3bbb4709a69c34ef3a5be/cosmos/testing/integration/rpc/eth_test.go#L48

we can improve it by setting up chain and client once and using `BeforeSuite` and `AfterSuite`. We can also use `SpecTimeout` and `NodeTimeout` to ensure that we are not spending too much time.

integration tests could use shared state of chain so we can verify it's working as expected over multiple concurrent scenarios

**Comment by itsdevbear** [comment]
good project will give this a spin when I get a chance

**Comment by itsdevbear** [comment]
or if an open sourceoooooor hits it first that works too
