### ISSUE TITLE
feat(cosmos): Bank Precompile

### ISSUE THREAD

**Issue by itsdevbear** [berachain/polaris#525]
Work with @calbera on implementing the bank precompile query and message functions.

**Comment by BrickBera** [comment]
todo:

all func in:
https://github.com/cosmos/cosmos-sdk/blob/main/x/bank/keeper/grpc_query.go

send, multi send in: 
https://github.com/cosmos/cosmos-sdk/blob/main/x/bank/keeper/msg_server.go
