### ISSUE TITLE
bug(eth): state changes during a tx that calls precompile does not persist

### ISSUE THREAD

**Issue by calbera** [berachain/polaris#538]
![image](https://user-images.githubusercontent.com/113940816/229850169-19938f40-db39-4d7c-9492-e3266232cb60.png)
After the precompile call successfully executes, and `amount` shares have been delegated to the `validatorAddress`, the mint of ERC20 tokens to msg.sender does not save. Further queries to `balanceOf` do not show the updated balance.

**Comment by itsdevbear** [comment]
@calbera test this tomorrow, but im 99% sure its the query context thing.
