### ISSUE TITLE
Unknown target specified: "install"

### ISSUE THREAD

**Issue by robertjuh** [berachain/polaris#584]
**Linux distro:**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

**go version:**
go1.20.3 linux/amd64

I followed every step from this guide: https://polaris.berachain.dev/docs/running-a-node/running-locally

After running 
`go run magefiles/setup/setup.go`

I added the gopath by executing:
`nano ~/.bashrc`

and adding this line:
`export PATH=$PATH:$(go env GOPATH)/bin`

Then i executed:
`mage install`

And i got this output:
`
root@vmi1275166:~/berachain/polaris# mage install
Unknown target specified: "install"
`

I can't proceed with the guide. 

Expected behavior: i follow every step in the guide flawlessly and the node will be up and running.

**Comment by calbera** [comment]
Hey thanks for posting the issue! This is an issue with our docs and our magefiles, I will push a fix asap.

**Comment by calbera** [comment]
@robertjuh Heres the fix https://github.com/berachain/polaris/pull/586/files, if you want to try locally. This fix will also be pushed up to main very soon.

**Comment by robertjuh** [comment]
Legend! will try it out once it is live
