### ISSUE TITLE
Error: running "./cosmos/runtime/localnode/init.sh " failed with exit code 2

### ISSUE THREAD

**Issue by robertjuh** [berachain/polaris#587]
Linux distro:
Distributor ID: Ubuntu
Description: Ubuntu 20.04.6 LTS
Release: 20.04
Codename: focal

go version:
go1.20.3 linux/amd64

I followed every step from this guide: https://polaris.berachain.dev/docs/running-a-node/running-locally

After running
`mage start`

it ends up in this error:
`Error: running "./cosmos/runtime/localnode/init.sh " failed with exit code 2
`

Let me know if you need to see the full output

**Comment by robertjuh** [comment]
chatgpt told me to do ls -l so heres the output:

root@vmi1275166:~/berachain/polaris# ls -l ./cosmos/runtime/localnode/init.sh
-rwxr-xr-x 1 root root 5694 Apr 28 00:55 ./cosmos/runtime/localnode/init.sh

**Comment by calbera** [comment]
Yea go ahead and past the full error log

**Comment by robertjuh** [comment]
root@vmi1275166:~/berachain/polaris# mage start
Building solidity contracts with foundry...
Building the Cosmos SDK chain...
Building the Playground chain...
INFO [04-28|01:05:21.546] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:21.546] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc001c32600
{"app_message":{"auth":{"accounts":[],"params":{"max_memo_characters":"256","sig_verify_cost_ed25519":"590","sig_verify_cost_secp256k1":"1000","tx_sig_limit":"7","tx_size_cost_per_byte":"10"}},"authz":{"authorization":[]},"bank":{"balances":[],"denom_metadata":[],"params":{"default_send_enabled":true,"send_enabled":[]},"send_enabled":[],"supply":[]},"consensus":null,"crisis":{"constant_fee":{"amount":"1000","denom":"stake"}},"distribution":{"delegator_starting_infos":[],"delegator_withdraw_infos":[],"fee_pool":{"community_pool":[]},"outstanding_rewards":[],"params":{"base_proposer_reward":"0.000000000000000000","bonus_proposer_reward":"0.000000000000000000","community_tax":"0.020000000000000000","withdraw_addr_enabled":true},"previous_proposer":"","validator_accumulated_commissions":[],"validator_current_rewards":[],"validator_historical_rewards":[],"validator_slash_events":[]},"erc20":{"params":{}},"evidence":{"evidence":[]},"evm":{"address_to_contract":{},"hash_to_code":{},"params":{"chain_config":"{\"chainId\":69420,\"homesteadBlock\":0,\"daoForkBlock\":0,\"daoForkSupport\":true,\"eip150Block\":0,\"eip150Hash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"eip155Block\":0,\"eip158Block\":0,\"byzantiumBlock\":0,\"constantinopleBlock\":0,\"petersburgBlock\":0,\"istanbulBlock\":0,\"berlinBlock\":0,\"londonBlock\":0,\"arrowGlacierBlock\":0,\"grayGlacierBlock\":0,\"mergeNetsplitBlock\":0,\"terminalTotalDifficulty\":0,\"terminalTotalDifficultyPassed\":true}","evm_denom":"abera","extra_eips":[]}},"feegrant":{"allowances":[]},"genutil":{"gen_txs":[]},"gov":{"constitution":"","deposit_params":null,"deposits":[],"params":{"burn_proposal_deposit_prevote":false,"burn_vote_quorum":false,"burn_vote_veto":true,"expedited_min_deposit":[{"amount":"50000000","denom":"stake"}],"expedited_threshold":"0.667000000000000000","expedited_voting_period":"86400s","max_deposit_period":"172800s","min_deposit":[{"amount":"10000000","denom":"stake"}],"min_initial_deposit_ratio":"0.000000000000000000","proposal_cancel_dest":"","proposal_cancel_ratio":"0.500000000000000000","quorum":"0.334000000000000000","threshold":"0.500000000000000000","veto_threshold":"0.334000000000000000","voting_period":"172800s"},"proposals":[],"starting_proposal_id":"1","tally_params":null,"votes":[],"voting_params":null},"group":{"group_members":[],"group_policies":[],"group_policy_seq":"0","group_seq":"0","groups":[],"proposal_seq":"0","proposals":[],"votes":[]},"mint":{"minter":{"annual_provisions":"0.000000000000000000","inflation":"0.130000000000000000"},"params":{"blocks_per_year":"6311520","goal_bonded":"0.670000000000000000","inflation_max":"0.200000000000000000","inflation_min":"0.070000000000000000","inflation_rate_change":"0.130000000000000000","mint_denom":"stake"}},"slashing":{"missed_blocks":[],"params":{"downtime_jail_duration":"600s","min_signed_per_window":"0.500000000000000000","signed_blocks_window":"100","slash_fraction_double_sign":"0.050000000000000000","slash_fraction_downtime":"0.010000000000000000"},"signing_infos":[]},"staking":{"delegations":[],"exported":false,"last_total_power":"0","last_validator_powers":[],"params":{"bond_denom":"stake","historical_entries":10000,"max_entries":7,"max_validators":100,"min_commission_rate":"0.000000000000000000","unbonding_time":"1814400s"},"redelegations":[],"unbonding_delegations":[],"validators":[]},"upgrade":{},"vesting":{}},"chain_id":"polaris-2061","gentxs_dir":"","moniker":"localtestnet","node_id":"7a6464ec024b5be092ee929f522c93ae36612d3c"}
INFO [04-28|01:05:21.931] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:21.931] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc00162f1a0
INFO [04-28|01:05:22.268] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:22.269] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc002d45800
INFO [04-28|01:05:22.637] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:22.637] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc002f47140

- address: polar1uvxnnzlht0zwc5yuvu7pt8dzy4tjhr5mskam23
  name: dev0
  pubkey: '{"@type":"/polaris.crypto.ethsecp256k1.v1.PubKey","key":"Ap/BwFOyJUNCj8sTTOj7fgo1DomueYmf+qbRXCsM6bn4"}'
  type: local


**Important** write this mnemonic phrase in a safe place.
It is the only way to recover your account if you ever forget your password.

give xxxx charge market alien xxxx eye olive wink relax yellow upon xxxx net husband wasp beauty theme tackle vast gather valley comfort camp
INFO [04-28|01:05:23.033] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:23.033] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc0032f3aa0

- address: polar1r3e7j0q3l3pt5mngr3lwe2ecjm90h6kn9a5sxx
  name: dev1
  pubkey: '{"@type":"/polaris.crypto.ethsecp256k1.v1.PubKey","key":"AtsPIPAibDQjJ+tPBSXpUYXNlk27tUN/pgyNE2WEyRme"}'
  type: local


**Important** write this mnemonic phrase in a safe place.
It is the only way to recover your account if you ever forget your password.

slide easy stable wreck senior gap field glove ostrich doctor horse movie pepper copy convince salon shield potato enroll fantasy length track juice dignity
INFO [04-28|01:05:23.428] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:23.428] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc00220d1a0

- address: polar14j5mhv8tuj5nhzxud4sdf0t886kq6knanywkt0
  name: dev2
  pubkey: '{"@type":"/polaris.crypto.ethsecp256k1.v1.PubKey","key":"AlxJ7xVq0Hq1WAX5qs85u1+Vc7h1ZW9Y74dHtpU8RTRt"}'
  type: local


**Important** write this mnemonic phrase in a safe place.
It is the only way to recover your account if you ever forget your password.

humor blame output team kidney timber volume alley lesson box nasty tide coach wrist woman grab mercy despair merit lady quiz lab wolf eternal
INFO [04-28|01:05:24.095] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:24.096] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc002f2f680
INFO [04-28|01:05:24.477] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:24.477] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc00248cde0
INFO [04-28|01:05:24.833] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:24.833] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc0035e14a0
INFO [04-28|01:05:25.173] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:25.173] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc002cb3560
INFO [04-28|01:05:25.494] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:25.494] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc0034ce5a0
Genesis transaction written to ".tmp/polard/config/gentx/gentx-7a6464ec024b5be092ee929f522c93ae36612d3c.json"
INFO [04-28|01:05:25.998] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:25.998] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc001744240
{"app_message":{"auth":{"accounts":[{"@type":"/cosmos.auth.v1beta1.BaseAccount","account_number":"0","address":"polar1uvxnnzlht0zwc5yuvu7pt8dzy4tjhr5mskam23","pub_key":null,"sequence":"0"},{"@type":"/cosmos.auth.v1beta1.BaseAccount","account_number":"1","address":"polar1r3e7j0q3l3pt5mngr3lwe2ecjm90h6kn9a5sxx","pub_key":null,"sequence":"0"},{"@type":"/cosmos.auth.v1beta1.BaseAccount","account_number":"2","address":"polar14j5mhv8tuj5nhzxud4sdf0t886kq6knanywkt0","pub_key":null,"sequence":"0"},{"@type":"/cosmos.auth.v1beta1.BaseAccount","account_number":"3","address":"polar1yrene6g2zwjttemf0c65fscg8w8c55w5vhc9hd","pub_key":null,"sequence":"0"}],"params":{"max_memo_characters":"256","sig_verify_cost_ed25519":"590","sig_verify_cost_secp256k1":"1000","tx_sig_limit":"7","tx_size_cost_per_byte":"10"}},"authz":{"authorization":[]},"bank":{"balances":[{"address":"polar1r3e7j0q3l3pt5mngr3lwe2ecjm90h6kn9a5sxx","coins":[{"amount":"100000000000000000000000000","denom":"abera"}]},{"address":"polar1yrene6g2zwjttemf0c65fscg8w8c55w5vhc9hd","coins":[{"amount":"69000000000000000000000000","denom":"abera"}]},{"address":"polar14j5mhv8tuj5nhzxud4sdf0t886kq6knanywkt0","coins":[{"amount":"100000000000000000000000000","denom":"abera"}]},{"address":"polar1uvxnnzlht0zwc5yuvu7pt8dzy4tjhr5mskam23","coins":[{"amount":"100000000000000000000000000","denom":"abera"}]}],"denom_metadata":[],"params":{"default_send_enabled":true,"send_enabled":[]},"send_enabled":[],"supply":[{"amount":"369000000000000000000000000","denom":"abera"}]},"consensus":null,"crisis":{"constant_fee":{"amount":"1000","denom":"abera"}},"distribution":{"delegator_starting_infos":[],"delegator_withdraw_infos":[],"fee_pool":{"community_pool":[]},"outstanding_rewards":[],"params":{"base_proposer_reward":"0.000000000000000000","bonus_proposer_reward":"0.000000000000000000","community_tax":"0.020000000000000000","withdraw_addr_enabled":true},"previous_proposer":"","validator_accumulated_commissions":[],"validator_current_rewards":[],"validator_historical_rewards":[],"validator_slash_events":[]},"erc20":{"params":{}},"evidence":{"evidence":[]},"evm":{"address_to_contract":{},"hash_to_code":{},"params":{"chain_config":"{\"chainId\":69420,\"homesteadBlock\":0,\"daoForkBlock\":0,\"daoForkSupport\":true,\"eip150Block\":0,\"eip150Hash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"eip155Block\":0,\"eip158Block\":0,\"byzantiumBlock\":0,\"constantinopleBlock\":0,\"petersburgBlock\":0,\"istanbulBlock\":0,\"berlinBlock\":0,\"londonBlock\":0,\"arrowGlacierBlock\":0,\"grayGlacierBlock\":0,\"mergeNetsplitBlock\":0,\"terminalTotalDifficulty\":0,\"terminalTotalDifficultyPassed\":true}","evm_denom":"abera","extra_eips":[]}},"feegrant":{"allowances":[]},"genutil":{"gen_txs":[{"auth_info":{"fee":{"amount":[],"gas_limit":"200000","granter":"","payer":""},"signer_infos":[{"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"public_key":{"@type":"/polaris.crypto.ethsecp256k1.v1.PubKey","key":"Ap/BwFOyJUNCj8sTTOj7fgo1DomueYmf+qbRXCsM6bn4"},"sequence":"0"}],"tip":null},"body":{"extension_options":[],"memo":"7a6464ec024b5be092ee929f522c93ae36612d3c@84.46.254.109:26656","messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","commission":{"max_change_rate":"0.010000000000000000","max_rate":"0.200000000000000000","rate":"0.100000000000000000"},"delegator_address":"","description":{"details":"","identity":"","moniker":"localtestnet","security_contact":"","website":""},"min_self_delegation":"1","pubkey":{"@type":"/cosmos.crypto.ed25519.PubKey","key":"vDlDv0vFt6z/ch0D/wMeP1nNJEvcClwbFxqz8alfa0I="},"validator_address":"polarvaloper1uvxnnzlht0zwc5yuvu7pt8dzy4tjhr5mvydap7","value":{"amount":"1000000000000000000000","denom":"abera"}}],"non_critical_extension_options":[],"timeout_height":"0"},"signatures":["nQVHwMgY7HYOJslSeYtiA5nW3YkF5XWN/+RCYZlBTDBEJJAJXk/08n8Dg7Xelv8t6YgP7/7LXFSPW2iui2dlMgA="]}]},"gov":{"constitution":"","deposit_params":{"min_deposit":[{"denom":"abera"}]},"deposits":[],"params":{"burn_proposal_deposit_prevote":false,"burn_vote_quorum":false,"burn_vote_veto":true,"expedited_min_deposit":[{"amount":"50000000","denom":"stake"}],"expedited_threshold":"0.667000000000000000","expedited_voting_period":"86400s","max_deposit_period":"172800s","min_deposit":[{"amount":"10000000","denom":"stake"}],"min_initial_deposit_ratio":"0.000000000000000000","proposal_cancel_dest":"","proposal_cancel_ratio":"0.500000000000000000","quorum":"0.334000000000000000","threshold":"0.500000000000000000","veto_threshold":"0.334000000000000000","voting_period":"172800s"},"proposals":[],"starting_proposal_id":"1","tally_params":null,"votes":[],"voting_params":null},"group":{"group_members":[],"group_policies":[],"group_policy_seq":"0","group_seq":"0","groups":[],"proposal_seq":"0","proposals":[],"votes":[]},"mint":{"minter":{"annual_provisions":"0.000000000000000000","inflation":"0.130000000000000000"},"params":{"blocks_per_year":"6311520","goal_bonded":"0.670000000000000000","inflation_max":"0.200000000000000000","inflation_min":"0.070000000000000000","inflation_rate_change":"0.130000000000000000","mint_denom":"abera"}},"slashing":{"missed_blocks":[],"params":{"downtime_jail_duration":"600s","min_signed_per_window":"0.500000000000000000","signed_blocks_window":"100","slash_fraction_double_sign":"0.050000000000000000","slash_fraction_downtime":"0.010000000000000000"},"signing_infos":[]},"staking":{"delegations":[],"exported":false,"last_total_power":"0","last_validator_powers":[],"params":{"bond_denom":"abera","historical_entries":10000,"max_entries":7,"max_validators":100,"min_commission_rate":"0.000000000000000000","unbonding_time":"1814400s"},"redelegations":[],"unbonding_delegations":[],"validators":[]},"upgrade":{},"vesting":{}},"chain_id":"polaris-2061","gentxs_dir":".tmp/polard/config/gentx","moniker":"localtestnet","node_id":"7a6464ec024b5be092ee929f522c93ae36612d3c"}
INFO [04-28|01:05:26.504] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:26.504] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc0022169c0
File at .tmp/polard/config/genesis.json is a valid genesis file
INFO [04-28|01:05:26.851] Gasprice oracle is ignoring threshold set threshold=2
INFO [04-28|01:05:26.851] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc001c32ba0
WARN [04-28|01:05:27.072] Sanitizing invalid gasprice oracle ignore price provided=0 updated=2
INFO [04-28|01:05:27.072] called eth.rpc.backend.SubscribeChainHeadEvent ch=0xc003bc1560
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc0022f5a20, params}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc0023010c0, feegrant}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc002311e30, distribution}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc002334e50, consensus}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc0022f5200, auth}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc00230a0d0, slashing}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc00230adc0, staking}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc0023340d0, mint}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc00231f700, upgrade}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc00231ff50, group}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc00232aae0, evm}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc00232b490, erc20}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc0022f4c30, bank}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc002310420, crisis}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc0023114b0, gov}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc00230b9c0, evidence}" version=0
1:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D is_lazy=false module=server store_key="KVStoreKey{0xc00231ed60, authz}" version=0
1:05AM INF starting node with ABCI CometBFT in-process module=server
1:05AM INF service start impl=multiAppConn module=proxy msg={}
1:05AM INF service start connection=query impl=localClient module=abci-client msg={}
1:05AM INF service start connection=snapshot impl=localClient module=abci-client msg={}
1:05AM INF service start connection=mempool impl=localClient module=abci-client msg={}
1:05AM INF service start connection=consensus impl=localClient module=abci-client msg={}
1:05AM INF service start impl=EventBus module=events msg={}
1:05AM INF service start impl=PubSub module=pubsub msg={}
1:05AM INF service start impl=IndexerService module=txindex msg={}
1:05AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=0.0.0
1:05AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
1:05AM INF InitChain chainID=polaris-2061 initialHeight=1 module=server
1:05AM INF initializing blockchain state from genesis.json module=server
1:05AM INF called eth.rpc.backend.ChainConfig module=polaris-geth
1:05AM INF called eth.rpc.backend.SubscribeLogsEvent ch="marshaling error: json: unsupported type: chan<- []*types.Log" module=polaris-geth
1:05AM INF called eth.rpc.backend.SubscribeRemovedLogsEvent ch="marshaling error: json: unsupported type: chan<- core.RemovedLogsEvent" module=polaris-geth
1:05AM INF called eth.rpc.backend.SubscribeChainEvent ch="marshaling error: json: unsupported type: chan<- core.ChainEvent" module=polaris-geth
1:05AM INF Starting peer-to-peer node instance=polard/linux-amd64/go1.20.3 module=polaris-geth
1:05AM INF New local node record id=88acd46f9076cc248ebd00bf6cc78fdf259734e4918b33561a573f3699d5783e ip=127.0.0.1 module=polaris-geth seq=1682636727122 tcp=0 udp=52464
1:05AM INF Started P2P networking module=polaris-geth self=enode://11de5228cf4755f60246899ad7a61e607d346e6a91890b0b0f432c1851b3e12f86b6989d2257a5bf467bf89e1cd10669c4f7c6773fb26d958fd485cc516077dd@127.0.0.1:0?discport=52464
panic: listen tcp 127.0.0.1:8545: bind: address already in use

goroutine 179 [running]:
pkg.berachain.dev/polaris/cosmos/x/evm.AppModule.InitGenesis({{}, _, {_, _}, {_, _}}, {{0x3a7f3f8, 0xc0001a8000}, {0x3a964a0, 0xc002961d00}, ...}, ...)
        /root/berachain/polaris/cosmos/x/evm/genesis.go:57 +0x14c
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x3a7f3f8, 0xc0001a8000}, {0x3a964a0, 0xc002961d00}, {{0x0, 0x0}, {0xc003bff6e0, 0xc}, 0x0, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.0-beta2.0.20230423204932-f0018246f107/types/module/module.go:466 +0x3b3
github.com/cosmos/cosmos-sdk/runtime.(*App).InitChainer(_, {{0x3a7f3f8, 0xc0001a8000}, {0x3a964a0, 0xc002961d00}, {{0x0, 0x0}, {0xc003bff6e0, 0xc}, 0x0, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.0-beta2.0.20230423204932-f0018246f107/runtime/app.go:152 +0x12e
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc001c95a00, {{0x21c65110, 0xedbdcf6b1, 0x0}, {0xc003bff6e0, 0xc}, 0xc001232940, {0x531a1f0, 0x0, 0x0}, ...})
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.0-beta2.0.20230423204932-f0018246f107/baseapp/abci.go:84 +0x5b5
github.com/cometbft/cometbft/abci/client.(*localClient).InitChainSync(0xc003c15320, {{0x21c65110, 0xedbdcf6b1, 0x0}, {0xc003bff6e0, 0xc}, 0xc001232940, {0x531a1f0, 0x0, 0x0}, ...})
        /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1-0.20230411132551-3a91d155e664/abci/client/local_client.go:275 +0x118
github.com/cometbft/cometbft/proxy.(*appConnConsensus).InitChainSync(0xc003c16ee8, {{0x21c65110, 0xedbdcf6b1, 0x0}, {0xc003bff6e0, 0xc}, 0xc001232940, {0x531a1f0, 0x0, 0x0}, ...})
        /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1-0.20230411132551-3a91d155e664/proxy/app_conn.go:85 +0x137
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x2da70ff, 0x6}}, {0xc003bff6e0, 0xc}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1-0.20230411132551-3a91d155e664/consensus/replay.go:319 +0xf18
github.com/cometbft/cometbft/consensus.(*Handshaker).Handshake(0xc0022cfdc0, {0x3a9a6c0, 0xc003a168c0})
        /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1-0.20230411132551-3a91d155e664/consensus/replay.go:268 +0x3ca
github.com/cometbft/cometbft/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2da70ff, 0x6}}, {0xc003bff6e0, 0xc}, 0x1, 0x0, ...}, ...)
        /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1-0.20230411132551-3a91d155e664/node/node.go:328 +0x198
github.com/cometbft/cometbft/node.NewNode(0xc00209e420, {0x3a69c10, 0xc003b31860}, 0xc003c010a0, {0x3a58160, 0xc003c162b8}, 0x1?, 0x531a1f0?, 0xc003c012d0, {0x3a82060, ...}, ...)
        /root/go/pkg/mod/github.com/cometbft/cometbft@v0.37.1-0.20230411132551-3a91d155e664/node/node.go:778 +0x56d
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x3a9c680, 0xc002130660}, 0x0, {0xc001814870, 0xc}, {0x3ab39a8, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.0-beta2.0.20230423204932-f0018246f107/server/start.go:324 +0x747
github.com/cosmos/cosmos-sdk/server.StartCmd.func2.2()
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.0-beta2.0.20230423204932-f0018246f107/server/start.go:150 +0x58
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile.func2()
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.0-beta2.0.20230423204932-f0018246f107/server/start.go:509 +0x29
created by github.com/cosmos/cosmos-sdk/server.wrapCPUProfile
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.0-beta2.0.20230423204932-f0018246f107/server/start.go:508 +0x24a
Error: running "./cosmos/runtime/localnode/init.sh " failed with exit code 2
root@vmi1275166:~/berachain/polaris#

**Comment by robertjuh** [comment]
@calbera here's the full log, i only partly obfuscated the key phrase

**Comment by unbanksytv** [comment]
following as I got the same Error: running "./cosmos/runtime/localnode/init.sh " failed with exit code 2

**Comment by itsdevbear** [comment]
`panic: listen tcp 127.0.0.1:8545: bind: address already in use` 

8545 is being held by another process,
