### ISSUE TITLE
bug(IBC): All SDK coins including via IBC must set denomMetadata

### ISSUE THREAD

**Issue by calbera** [berachain/polaris#682]
For any IBC bridged SDK coins, we need to ensure setting denom metadata for the incoming coin

_Originally posted by @calbera in https://github.com/berachain/polaris/issues/661#issuecomment-1542273415_

**Comment by ameya-deshmukh** [comment]
@calbera is this open to take up?

**Comment by itsdevbear** [comment]
more work required to figure out the dev ux of the `bank` module before we can dive into this
