### ISSUE TITLE
failed `testing/e2e/polariserc20`

### ISSUE THREAD

**Issue by iprotoni** [berachain/polaris#949]
I'm getting failures with polariserc20 test suites. screenshot attached.
![Screenshot from 2023-07-31 09-58-50](https://github.com/berachain/polaris/assets/120520990/793844a8-d706-489d-85cb-2ce6e026a8ed)

**Comment by itsdevbear** [comment]
we need to fix the documentation here aaahhhhhhh

try `mage cosmos:docker base arm64` then `mage cosmos:docker base localnet`

**Comment by iprotoni** [comment]
I'm getting error with `mage cosmos:docker base arm64`
` => ERROR [builder  2/14] RUN set -eux;     apk add git linux-headers ca-certificates build-base                                                                                                      3.2s`
screenshot attached;
![image](https://github.com/berachain/polaris/assets/120520990/1dd98b42-104f-4196-b927-57c61fef0ae3)
